### ISSUE TITLE
Arc

### ISSUE THREAD

**Issue by freeman128** [strongloop/generator-loopback#123]
How can I run loopback arc if you installed it with yeoman ? Documentation is missing this part. 

Create a model in your app
    $ yo loopback:model
  Compose your API, run, deploy, profile, and monitor it with Arc
    $ slc arc
  Run the app
    $ node .

**Comment by jannyHou** [comment]
hey @freeman128 thanks for your suggestion!
All of our commands are list here in doc:
https://docs.strongloop.com/pages/releaseview.action?pageId=3836281
I will see if we need to add `slc arc` there!

BTW, In my opinion an individual dependency repository  is not the best place to explain everything :) because users always go to our [detailed doc website](https://docs.strongloop.com/display/SL/Installing+StrongLoop) to follow tutorials to get started. And as you list here, generators always print necessary information on screen to give users better guides.
