### ISSUE TITLE
Fix the skipped test cases after upgrading to yeoman-generator@3.x

### ISSUE THREAD

**Issue by jannyHou** [strongloop/generator-loopback#389]
# Description/Steps to reproduce

A follow up issue of https://github.com/strongloop/generator-loopback/pull/363
Fix the 2 skipped tests in `datasource.test.js`

# Expected result

The 2 skipped tests pass

**Comment by dhmlau** [comment]
@jannyHou , after all the tests passed in `generator-loopback`, any outstanding tasks need to be done in order to release a semver-major version of `loopback-cli` to make use of the new `generator-loopback`?

**Comment by jannyHou** [comment]
@dhmlau I would say this task shouldn't block the semver-major release of `loopback-cli`.

**Comment by bajtos** [comment]
This task has been sitting in backlog for ~6 months by now and there was no problem (regression) caused by the fact that we are skipping some of the tests. Considering how little changes we are making in generator-loopback anyways, I am proposing to close this issue as "wontfix".

@jannyHou thoughts?

**Comment by jannyHou** [comment]
I manually verified those two commands work on local, the time was spent on figuring out how to use yeoman-test functions(haven't found a good solution yet). 
I am good to close it.

**Comment by dhmlau** [comment]
Closing per [above comment](https://github.com/strongloop/generator-loopback/issues/389#issuecomment-461829478).
