### ISSUE TITLE
Add unit test to ensure sub-generators can be run from any subdir

### ISSUE THREAD

**Issue by superkhau** [strongloop/generator-loopback#97]
Connected to #96

**Comment by bajtos** [comment]
>  I will need your help in figuring out how to simulate `slc loopback:model`

Look at `test/model.test.js`. In your test, you will need to `chdir` to a different directory before running the generator. I think you don't need to change the path back because yeoman test helpers do that for you - see https://github.com/yeoman/generator/blob/461a181d9fa463d139faed3456ce33f5a993ca73/lib/test/helpers.js#L166-L185

**Comment by superkhau** [comment]
@gunjpan Reassigning to you since you can probably take this one on (and you are the repo expert here anyways).
