### ISSUE TITLE
slc loopback:* not showing models from other folders present on model-config.json

### ISSUE THREAD

**Issue by lius** [strongloop/generator-loopback#98]
I'm organising the models in subfolders inside common/models, registering each one on model-config.json (_meta.sources property). The application runs and works fine, but these models are not showed on slc loopback:* commands, just the others ones (default from LB).

strongloop: 2.10.3
loopback: 2.13.0
juggler: 2.19.0

**Comment by bajtos** [comment]
Thank you for reporting the issue. I am afraid I don't fully understand your scenario. Please provide us with an application and steps to reproduce the issue locally, as described in [Reporting Issues](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report).

**Comment by lius** [comment]
Ok.

Em seg, 30 de mar de 2015 às 10:35, Miroslav Bajtoš <
notifications@github.com> escreveu:

**Comment by miteshsondhi** [comment]
git@github.com:miteshsondhi/bug-dir-models.git

Clone the repo and try slc:loopback. It does not show "test" model. But app is working fine.

**Comment by bajtos** [comment]
@miteshsondhi thank you for the example repo, now I understand the problem.

The thing is, `slc loopback` tooling supports only one opinionated project layout at the moment, where the location of model files is hard-coded as `models/*.json`. As a rule of thumb, if the model was not created using `slc loopback:model`, then we don't guarantee that it will be picked up.

Let me explain the difference between runtime and `slc loopback:model`. At runtime, the application calls [loopback-boot](https://github.com/strongloop/loopback-boot) to load all models and datasources. While this component has some opinions too, it's very flexible when it comes to the directory layout and that's why your example app works. On the other hand, `slc loopback` has to read and write configuration files and that adds a lot of complexity. To keep the implementation costs low, we decided to support only a subset of valid project layouts.

I am closing this issue as "won't fix". However, if there is a volunteer willing to improve the tooling to support custom model locations, then I am happy to reopen this issue and provide any help & guidance as needed.
